# SPDX-FileCopyrightText: 2026 [ernolf] Raphael Gradenwitz <raphael.gradenwitz@googlemail.com>
# SPDX-License-Identifier: AGPL-3.0-or-later
version = 1
SPDX-PackageName = "files_sharing_raw"
SPDX-PackageSupplier = "[ernolf] Raphael Gradenwitz <raphael.gradenwitz@googlemail.com>"
SPDX-PackageDownloadLocation = "https://github.com/ernolf/files_sharing_raw"

[[annotations]]
path = ["composer.json", "composer.lock", "vendor-bin/*/composer.json", "package.json", "package-lock.json"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024-2026 [ernolf] Raphael Gradenwitz"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = [".github/FUNDING.yml", ".tx/config", "l10n/.gitkeep"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024-2026 [ernolf] Raphael Gradenwitz"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = ["l10n/**.js", "l10n/**.json"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Nextcloud translators"
SPDX-License-Identifier = "AGPL-3.0-or-later"
